### ISSUE TITLE
localhost 

### ISSUE THREAD

**Issue by MGD713** [fuegovic/chatgpt-clone-local-installer#1]
Hello,

I finished the install for the clone but when I try and run it (I tried both the first and second options on the first interface), I get an error saying that localhost refused to connect. Any help would be greatly appreciated. Thank you!

Matt

![image](https://github.com/fuegovic/chatgpt-clone-local-installer/assets/114160422/2f7064a8-a5c7-4576-be84-81776a601b90)

**Comment by fuegovic** [comment]
Hi Matt
, to be able to help you I will need you to send me a screenshot of one of the minimized command prompt window

look for this icon (or something similar)
![image](https://github.com/fuegovic/chatgpt-clone-local-installer/assets/32828263/858cf399-4561-4107-9ded-9510fcb9a0ba)

and open the minimized windows, look for the window that looks like this:
![image](https://github.com/fuegovic/chatgpt-clone-local-installer/assets/32828263/cf52e419-f0d0-4621-9435-538daae76104)

**Comment by MGD713** [comment]
Hi, thank you for the quick response. Here you go! 

![image](https://github.com/fuegovic/chatgpt-clone-local-installer/assets/114160422/89c825cb-459e-444f-93ee-777ab9e0b067)

**Comment by fuegovic** [comment]
I know the problem, it's an authentification error with the mongo database.
The most frequent cause is when people did not remove `<` `>` from around the password when entering the `MONGO_URI` string. It's an easy fix.

- Go to your install folder (c:\chatgpt-clone)
- go inside the `api` folder
- look for the file named `.env`
- open this file in a text editor (like notepad)
- look for this line `MONGO_URI="mongodb+srv://username:password@chatgpt-clone.qwertyq.mongodb.net/?retryWrites=true"`
- make sure that the formating follow the example above (username:password, without < >, ends at `=true`)
- save the file
- try to start it again

You should be able to start it once the mongodb strings is fixed, please let me know if it worked!

**Comment by MGD713** [comment]
It worked, thank you!

**Comment by fuegovic** [comment]
Your welcome!
